require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'UncompressExample' do
  use_frameworks!

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'uncompress-react-native', :path => '../..'

  target 'UncompressExampleTests' do
    inherit! :complete

    pod 'Nimble'
  end
end
